### ISSUE TITLE
can't convert cuda:0 device type tensor to numpy

### ISSUE THREAD

**Issue by centurions** [HCIILAB/Scene-Text-Recognition-Recommendations#2]
Traceback (most recent call last):
  File "main.py", line 228, in <module>
    main(args)
  File "main.py", line 185, in main
    evaluator.evaluate(test_loader, step=0, tfLogger=eval_tfLogger)
  File "D:\trainocr\ocr\Scene-Text-Recognition-Recommendations\Framework\lib\evaluators.py", line 70, in evaluate
    losses = np.sum(losses) / (1.0 * (len(data_loader)-1)*batch_size)
  File "<__array_function__ internals>", line 180, in sum
  File "C:\secsys\snake\lib\site-packages\numpy\core\fromnumeric.py", line 2296, in sum
    return _wrapreduction(a, np.add, 'sum', axis, dtype, out, keepdims=keepdims,
  File "C:\secsys\snake\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "C:\secsys\snake\lib\site-packages\torch\_tensor.py", line 643, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by Mountchicken** [comment]
Sorry for the late reply. It seems that the loss calculated is on GPU and np.sum( ) only takes CPU input. I haven't meet this problem before, but you can try to use: 
losses = np.sum(lossess.cpu()) / (1.0 * (len(data_loader)-1)*batch_size)
 insteed

**Comment by centurions** [comment]
Thank youuuuu very much !!!

**Comment by centurions** [comment]
losses = np.sum(losses.cpu()) / (1.0 * (len(data_loader)-1)*batch_size)
AttributeError: 'list' object has no attribute 'cpu'

**Comment by Mountchicken** [comment]
try:
losses = np.sum( [loss.cpu() for loss in losses]) / (1.0 * (len(data_loader)-1)*batch_size) ?
losses is a list here.
