### ISSUE TITLE
i have problem to run your project

### ISSUE THREAD

**Issue by smartking260** [HCIILAB/Scene-Text-Recognition-Recommendations#3]
hi .i have problem wile running project ,can you help me?
this is my error:

pt/anaconda3/bin/python "/Users/ghasempirani/Downloads/Scene-Text-Recognition-Recommendations-main 2/Framewor
k/main.py"
Traceback (most recent call last):
  File "/Users/ghasempirani/Downloads/Scene-Text-Recognition-Recommendations-main 2/Framework/main.py", line 22, in <module>
    from lib.models.model_builder_Attention import ModelBuilder_Att
  File "/Users/ghasempirani/Downloads/Scene-Text-Recognition-Recommendations-main 2/Framework/lib/models/model_builder_Attention.py", line 6, in <module>
    from .decoder.attention_recognition_head import AttentionRecognitionHead
  File "/Users/ghasempirani/Downloads/Scene-Text-Recognition-Recommendations-main 2/Framework/lib/models/decoder/attention_recognition_head.py", line 10, in <module>
    device =torch.device('cuda' if torch.cuda.is_available() else 'gpu')
RuntimeError: Expected one of cpu, cuda, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mlc, xla, lazy, vulkan, meta, hpu device type at start of device string: gpu
(base) ghasempirani@Ghasems-MacBook-Air Scene-Text-Recognition-Recommendations-main 2 %

**Comment by Mountchicken** [comment]
Hi @smartking260 
Sorry, that's a typo mistake. The correct code at `line10` in `Framework/lib/models/decoder/attention_recognition_head.py` should be:
```python
device =torch.device('cuda' if torch.cuda.is_available() else 'cpu')
```
- Fixed in the newest version.
